# Generated by Django 4.2.6 on 2023-10-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_trabajos_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajos_Clasificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('clasificacion', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
            },
        ),
    ]
